theme: jekyll-theme-minimal
title: ADA Apes Strong Together Website
description: ADA : Apes Strong Together final project
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Example
    url: example
